name: puked
description: A sophisticated tool for autonomous driving PMs to record ride comfort.
version: 2.0.2+13

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Sensors & Location
  sensors_plus: ^6.1.1
  geolocator: ^13.0.1
  
  # NEW: Pure Dart Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  
  # Utils & Math
  http: ^1.2.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2
  vector_math: ^2.1.4
  json_annotation: ^4.9.0
  intl: ^0.20.2
  share_plus: ^10.1.4
  uuid: ^4.5.1
  wakelock_plus: ^1.2.11
  ota_update: ^7.1.0
  flutter_svg: ^2.0.10+1
  pocketbase: ^0.23.0+1
  image_picker: ^1.1.2

  # Data Visualization & UI Components
  fl_chart: ^0.70.2
  smooth_page_indicator: ^1.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  android_12:
    image: "assets/images/logo.png"
    color: "#ffffff"
  fullscreen: true
